# Base image
FROM ubuntu:22.04

# Avoid interactive prompts during install
ENV DEBIAN_FRONTEND=noninteractive

# Install core tools: Python, pip, curl, Java 17, Maven, Git
RUN apt update && \
    apt install -y python3 python3-pip curl unzip zip git software-properties-common && \
    add-apt-repository ppa:openjdk-r/ppa && \
    apt update && \
    apt install -y openjdk-17-jdk maven && \
    pip3 install awscli awscli-local && \
    apt clean

# Set up working directory
WORKDIR /app

# Default shell
CMD ["/bin/bash"]
